In [ ]:
NAME       :DHEEPIKA.I
REGISTER NO:21UAI023
SUBJECT     :BASIC OF MACHINE LEARNING
ASSIGNMENT-3

In [1]:
#using score dataset

In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [13]:
df = pd.read_csv("C:/Users/User/Downloads/test_score.csv")
df

experience  test_score  interview_score  salary
0           2         8.0                9   50000
1           1         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         NaN                7   72000
7          11         7.0                6   60000

In [15]:
df.test_score.median()

8.0

In [16]:
df.test_score = df.test_score.fillna(df.test_score.median())
df

experience  test_score  interview_score  salary
0           2         8.0                9   50000
1           1         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                6   60000

In [18]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('salary',axis='columns'),df.salary)

LinearRegression()

In [19]:
reg.coef_

array([2248.37403744, 2538.21886194, 2373.19046102])

In [20]:
reg.intercept_

10893.032255056627

In [21]:
reg.predict([[8,7,9]])

C:\Users\User\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([68006.27073734])

In [22]:
reg.predict([[7,6,10]])

C:\Users\User\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([65592.86829898])

In [23]:
#using Home Price

In [24]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [25]:
df = pd.read_csv("C:/Users/User/Downloads/homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [26]:
df.bedrooms.median()

4.0

In [27]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [28]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('price',axis='columns'),df.price)

LinearRegression()

In [29]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [30]:
reg.intercept_

221323.00186540425

In [31]:
reg.predict([[3000, 3, 40]])

C:\Users\User\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [32]:
reg.predict([[2500, 4, 5]])

C:\Users\User\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])